version: '2'
services:
 nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
   - "80:80"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
   - DEFAULT_HOST=www.*
 backend:
  image: node:latest
  command: node /app
  container_name: backend
  expose:
   - "8000"
  volumes:
   - ./backend:/app
  environment:
   - VIRTUAL_HOST=api.*
 frontend:
  image: node:latest
  command: node /app
  container_name: frontend
  expose:
   - "8080"
  volumes:
   - ./frontend:/app
  environment:
   - VIRTUAL_HOST=www.*
