version: '2'
services:
 nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
   - "80:80"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
   - DEFAULT_HOST=www.*

 mongodb:
  image: mongo:latest
  container_name: mongodb
  ports:
   - "27017:27017"
  volumes:
   - ./data/db:/data/db

 backend:
  image: node:latest
  working_dir: /app
  command: bash -c "npm install -q && npm start"
  container_name: backend
  depends_on:
   - nginx-proxy
   - mongodb
  links:
   - mongodb
  expose:
   - "3000"
  volumes:
   - ./backend:/app
   - ./shared:/shared
  environment:
   - VIRTUAL_HOST=api.*
   - VIRTUAL_PORT=3000

 frontend:
  image: node:latest
  working_dir: /app
  command: bash -c "npm install -q && npm start"
  container_name: frontend
  depends_on:
   - nginx-proxy
   - backend
  expose:
   - "3000"
  ports:
   - "8042:3001"
  volumes:
   - ./frontend:/app
   - ./shared:/shared
  environment:
   - VIRTUAL_HOST=www.*
   - VIRTUAL_PORT=3000
